// Generated by fix_pages.py

export function generateStaticParams() {
  return [{ "orderId": "dummy" }];
}

interface PageProps {
  params: Promise<{ orderId: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

export default async function CheckoutSuccessOrderidPage({ params }: PageProps) {
  const { orderId } = await params;
  return (
    <div className="container-site py-12">
      <h1 className="text-3xl font-serif text-green-950 font-bold mb-4">CheckoutSuccessOrderidPage</h1>
      <p className="text-ink-muted">TODO: Implement page for route: <code className="bg-cream px-2 py-1 rounded text-sm">checkout/success/[orderId]</code></p>
      <p className="text-ink-subtle mt-2">Current parameters: orderId = {orderId}</p>
    </div>
  );
}
