// Generated by fix_pages.py
export default function AdminCouponsPage() {
  return (
    <div className="container-site py-12">
      <h1 className="text-3xl font-serif text-green-950 font-bold mb-4">AdminCouponsPage</h1>
      <p className="text-ink-muted">TODO: Implement page for route: <code className="bg-cream px-2 py-1 rounded text-sm">admin/coupons</code></p>
    </div>
  );
}
